### ISSUE TITLE
启动arduino.launch报错

### ISSUE THREAD

**Issue by a821101426** [LowPower-Center/Arduino#1]
from ros_arduino_python.arduino_sensors import *和from ros_arduino_python.base_controller import BaseController出现警告，并且执行launch文件后报错ModuleNotFoundError: No module named 'ros_arduino_python.arduino_sensors'

**Comment by LowPower-Center** [comment]
尝试一下先在工作空间安装此软件包、激活工作空间，再运行启动文件。

**Comment by a821101426** [comment]
![N@K9JLT{R_D1DS7FY4B ZME](https://user-images.githubusercontent.com/117722094/234012041-1c0ca86b-ba48-426e-8518-b652694bfb97.png)
arduino_node.py报出的警告，目前我不知道什么原因

**Comment by shouji000** [comment]
No module named 'ros_arduino_python.arduino_sensors'这个问题有解决吗，大佬怎样才能联系到你呀

**Comment by LowPower-Center** [comment]
在ros_arduino_python文件夹下丢失了两个文件arduino_sensors.py 和 base_controller.py导致了该问题。可以考虑去原作者仓库寻找这两个文件https://github.com/hbrobotics/ros_arduino_bridge
此仓库本地源文件已丢失，暂无法修复。

**Comment by shouji000** [comment]
可以加个微信吗，哈哈哈，志同道合的好友，这个问题我已经解决了，太感谢了，要是您愿意加的话，15962063926就是我的微信号



在 2023-07-15 14:58:55，"某S姓男子" ***@***.***> 写道：

在ros_arduino_python文件夹下丢失了两个文件arduino_sensors.py 和 base_controller.py导致了该问题。可以考虑去原作者仓库寻找这两个文件https://github.com/hbrobotics/ros_arduino_bridge/。此仓库本地源文件已丢失，暂无法修复。
